version: '3'

services:
  instance:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: starrail-auto
    network_mode: bridge
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      TZ: Asia/Shanghai
